/**
 * SubConverter 资源常量
 * 包含内置的后端地址和配置文件
 */

export const SUBCONVERTER_ASSETS = {
    backends: [
        { id: 1, name: 'CM负载均衡后端【vless reality+hy1+hy2】', url: 'subapi.cmliussss.net', is_default: true },
        { id: 2, name: 'CM应急备用后端【vless reality+hy1+hy2】', url: 'subapi.fxxk.dedyn.io', is_default: false },
        { id: 3, name: '肥羊增强型后端【vless reality+hy1+hy2】', url: 'url.v1.mk', is_default: false },
        { id: 4, name: '肥羊备用后端【vless reality+hy1+hy2】', url: 'sub.d1.mk', is_default: false },
        { id: 5, name: 'nameless13提供', url: 'www.nameless13.com', is_default: false },
        { id: 6, name: 'subconverter作者提供', url: 'sub.xeton.dev', is_default: false },
        { id: 7, name: 'sub-web作者提供', url: 'api.wcc.best', is_default: false }
    ],
    configs: [
        // ACL4SSR Group (100-399 roughly, mostly ACL4SSR related)
        { id: 101, name: 'CM_Online 默认版 识别港美地区(与Github同步)', url: 'https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/config/ACL4SSR_Online.ini', group: 'ACL4SSR', is_default: true },
        { id: 102, name: 'CM_Online_MultiCountry 识别港美地区 负载均衡(与Github同步)', url: 'https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/config/ACL4SSR_Online_MultiCountry.ini', group: 'ACL4SSR', is_default: false },
        { id: 103, name: 'CM_Online_MultiCountry_CF 识别港美地区、CloudFlareCDN 负载均衡 Worker节点专用(与Github同步)', url: 'https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/config/ACL4SSR_Online_MultiCountry_CF.ini', group: 'ACL4SSR', is_default: false },
        { id: 104, name: 'CM_Online_Full 识别多地区分组(与Github同步)', url: 'https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/config/ACL4SSR_Online_Full.ini', group: 'ACL4SSR', is_default: false },
        { id: 105, name: 'CM_Online_Full_CF 识别多地区、CloudFlareCDN 分组 Worker节点专用(与Github同步)', url: 'https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/config/ACL4SSR_Online_Full_CF.ini', group: 'ACL4SSR', is_default: false },
        { id: 106, name: 'CM_Online_Full_MultiMode 识别多地区 负载均衡(与Github同步)', url: 'https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/config/ACL4SSR_Online_Full_MultiMode.ini', group: 'ACL4SSR', is_default: false },
        { id: 107, name: 'CM_Online_Full_MultiMode_CF 识别多地区、CloudFlareCDN 负载均衡 Worker节点专用(与Github同步)', url: 'https://raw.githubusercontent.com/cmliu/ACL4SSR/main/Clash/config/ACL4SSR_Online_Full_MultiMode_CF.ini', group: 'ACL4SSR', is_default: false },

        // Default / General (200-299)
        { id: 201, name: '默认', url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full_NoAuto.ini', group: '通用', is_default: false },
        { id: 202, name: '默认（自动测速）', url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full_AdblockPlus.ini', group: '通用', is_default: false },
        { id: 203, name: '默认（索尼电视专用）', url: 'https://raw.githubusercontent.com/youshandefeiyang/webcdn/main/SONY.ini', group: '通用', is_default: false },
        { id: 204, name: '默认（附带用于 Clash 的 AdGuard DNS）', url: 'https://gist.githubusercontent.com/tindy2013/1fa08640a9088ac8652dbd40c5d2715b/raw/default_with_clash_adg.yml', group: '通用', is_default: false },
        { id: 205, name: 'ACL_全分组 Dream修改版', url: 'https://raw.githubusercontent.com/WC-Dream/ACL4SSR/WD/Clash/config/ACL4SSR_Online_Full_Dream.ini', group: 'ACL4SSR Mod', is_default: false },
        { id: 206, name: 'ACL_精简分组 Dream修改版', url: 'https://raw.githubusercontent.com/WC-Dream/ACL4SSR/WD/Clash/config/ACL4SSR_Mini_Dream.ini', group: 'ACL4SSR Mod', is_default: false },
        { id: 207, name: 'emby-TikTok-流媒体分组-去广告加强版', url: 'https://raw.githubusercontent.com/justdoiting/ClashRule/main/GeneralClashRule.ini', group: '流媒体', is_default: false },
        { id: 208, name: '流媒体通用分组', url: 'https://raw.githubusercontent.com/cutethotw/ClashRule/main/GeneralClashRule.ini', group: '流媒体', is_default: false },

        // More ACL4SSR (300-399)
        { id: 301, name: 'ACL_默认版', url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online.ini', group: 'ACL4SSR', is_default: false },
        { id: 302, name: 'ACL_无测速版', url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_NoAuto.ini', group: 'ACL4SSR', is_default: false },
        { id: 303, name: 'ACL_去广告版', url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_AdblockPlus.ini', group: 'ACL4SSR', is_default: false },
        { id: 304, name: 'ACL_多国家版', url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_MultiCountry.ini', group: 'ACL4SSR', is_default: false },
        { id: 305, name: 'ACL_无Reject版', url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_NoReject.ini', group: 'ACL4SSR', is_default: false },
        { id: 306, name: 'ACL_无测速精简版', url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Mini_NoAuto.ini', group: 'ACL4SSR', is_default: false },
        { id: 307, name: 'ACL_全分组版', url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full.ini', group: 'ACL4SSR', is_default: false },
        { id: 308, name: 'ACL_全分组谷歌版', url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full_Google.ini', group: 'ACL4SSR', is_default: false },
        { id: 309, name: 'ACL_全分组多模式版', url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full_MultiMode.ini', group: 'ACL4SSR', is_default: false },
        { id: 310, name: 'ACL_全分组奈飞版', url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full_Netflix.ini', group: 'ACL4SSR', is_default: false },
        { id: 311, name: 'ACL_精简版', url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Mini.ini', group: 'ACL4SSR', is_default: false },
        { id: 312, name: 'ACL_去广告精简版', url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Mini_AdblockPlus.ini', group: 'ACL4SSR', is_default: false },
        { id: 313, name: 'ACL_Fallback精简版', url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Mini_Fallback.ini', group: 'ACL4SSR', is_default: false },
        { id: 314, name: 'ACL_多国家精简版', url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Mini_MultiCountry.ini', group: 'ACL4SSR', is_default: false },
        { id: 315, name: 'ACL_多模式精简版', url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Mini_MultiMode.ini', group: 'ACL4SSR', is_default: false },

        // Other Rules (400-499)
        { id: 401, name: '常规规则', url: 'https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rule_config/ZHANG.ini', group: '其他规则', is_default: false },
        { id: 402, name: '酷酷自用', url: 'https://raw.githubusercontent.com/xiaoshenxian233/cool/rule/complex.ini', group: '其他规则', is_default: false },
        { id: 403, name: 'PharosPro无测速', url: 'https://subweb.s3.fr-par.scw.cloud/RemoteConfig/special/phaors.ini', group: '其他规则', is_default: false },
        { id: 404, name: '分区域故障转移', url: 'https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rule_config/ZHANG_Area_Fallback.ini', group: '其他规则', is_default: false },
        { id: 405, name: '分区域自动测速', url: 'https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rule_config/ZHANG_Area_Urltest.ini', group: '其他规则', is_default: false },
        { id: 406, name: '分区域无自动测速', url: 'https://raw.githubusercontent.com/flyhigherpi/merlinclash_clash_related/master/Rule_config/ZHANG_Area_NoAuto.ini', group: '其他规则', is_default: false },
        { id: 407, name: 'OoHHHHHHH', url: 'https://raw.githubusercontent.com/OoHHHHHHH/ini/master/config.ini', group: '其他规则', is_default: false },
        { id: 408, name: 'CFW-TAP', url: 'https://raw.githubusercontent.com/OoHHHHHHH/ini/master/cfw-tap.ini', group: '其他规则', is_default: false },
        { id: 409, name: 'lhl77全分组（定期更新）', url: 'https://raw.githubusercontent.com/lhl77/sub-ini/main/tsutsu-full.ini', group: '其他规则', is_default: false },
        { id: 410, name: 'lhl77简易版（定期更新）', url: 'https://raw.githubusercontent.com/lhl77/sub-ini/main/tsutsu-mini-gfw.ini', group: '其他规则', is_default: false },
        { id: 411, name: 'ConnersHua 神机规则 Outbound', url: 'https://gist.githubusercontent.com/tindy2013/1fa08640a9088ac8652dbd40c5d2715b/raw/connershua_new.ini', group: '神机规则', is_default: false },
        { id: 412, name: 'ConnersHua 神机规则 Inbound 回国专用', url: 'https://gist.githubusercontent.com/tindy2013/1fa08640a9088ac8652dbd40c5d2715b/raw/connershua_backtocn.ini', group: '神机规则', is_default: false },
        { id: 413, name: 'lhie1 洞主规则（使用 Clash 分组规则）', url: 'https://gist.githubusercontent.com/tindy2013/1fa08640a9088ac8652dbd40c5d2715b/raw/lhie1_clash.ini', group: '洞主规则', is_default: false },
        { id: 414, name: 'lhie1 洞主规则完整版', url: 'https://gist.githubusercontent.com/tindy2013/1fa08640a9088ac8652dbd40c5d2715b/raw/lhie1_dler.ini', group: '洞主规则', is_default: false },
        { id: 415, name: 'eHpo1 规则', url: 'https://gist.githubusercontent.com/tindy2013/1fa08640a9088ac8652dbd40c5d2715b/raw/ehpo1_main.ini', group: '其他规则', is_default: false },
        { id: 416, name: '多策略组默认白名单模式', url: 'https://raw.nameless13.com/api/public/dl/ROzQqi2S/white.ini', group: '其他规则', is_default: false },
        { id: 417, name: '多策略组可以有效减少审计触发', url: 'https://raw.nameless13.com/api/public/dl/ptLeiO3S/mayinggfw.ini', group: '其他规则', is_default: false },
        { id: 418, name: '精简策略默认白名单', url: 'https://raw.nameless13.com/api/public/dl/FWSh3dXz/easy3.ini', group: '其他规则', is_default: false },
        { id: 419, name: '多策略增加SMTP策略', url: 'https://raw.nameless13.com/api/public/dl/L_-vxO7I/youtube.ini', group: '其他规则', is_default: false },
        { id: 420, name: '无策略入门推荐', url: 'https://raw.nameless13.com/api/public/dl/zKF9vFbb/easy.ini', group: '其他规则', is_default: false },
        { id: 421, name: '无策略入门推荐国家分组', url: 'https://raw.nameless13.com/api/public/dl/E69bzCaE/easy2.ini', group: '其他规则', is_default: false },
        { id: 422, name: '无策略仅IPIP CN + Final', url: 'https://raw.nameless13.com/api/public/dl/XHr0miMg/ipip.ini', group: '其他规则', is_default: false },
        { id: 423, name: '无策略魅影vip分组', url: 'https://raw.nameless13.com/api/public/dl/BBnfb5lD/MAYINGVIP.ini', group: '其他规则', is_default: false },
        { id: 424, name: '品云专属配置（仅香港区域分组）', url: 'https://raw.githubusercontent.com/Mazeorz/airports/master/Clash/Examine.ini', group: '定制规则', is_default: false },
        { id: 425, name: '品云专属配置（全地域分组）', url: 'https://raw.githubusercontent.com/Mazeorz/airports/master/Clash/Examine_Full.ini', group: '定制规则', is_default: false },
        { id: 426, name: 'nzw9314 规则', url: 'https://gist.githubusercontent.com/tindy2013/1fa08640a9088ac8652dbd40c5d2715b/raw/nzw9314_custom.ini', group: '定制规则', is_default: false },
        { id: 427, name: 'maicoo-l 规则', url: 'https://gist.githubusercontent.com/tindy2013/1fa08640a9088ac8652dbd40c5d2715b/raw/maicoo-l_custom.ini', group: '定制规则', is_default: false },
        { id: 428, name: 'DlerCloud Platinum 李哥定制规则', url: 'https://gist.githubusercontent.com/tindy2013/1fa08640a9088ac8652dbd40c5d2715b/raw/dlercloud_lige_platinum.ini', group: '定制规则', is_default: false },
        { id: 429, name: 'DlerCloud Gold 李哥定制规则', url: 'https://gist.githubusercontent.com/tindy2013/1fa08640a9088ac8652dbd40c5d2715b/raw/dlercloud_lige_gold.ini', group: '定制规则', is_default: false },
        { id: 430, name: 'DlerCloud Silver 李哥定制规则', url: 'https://gist.githubusercontent.com/tindy2013/1fa08640a9088ac8652dbd40c5d2715b/raw/dlercloud_lige_silver.ini', group: '定制规则', is_default: false },
        { id: 431, name: 'ProxyStorage自用', url: 'https://unpkg.com/proxy-script/config/Clash/clash.ini', group: '定制规则', is_default: false },
        { id: 432, name: 'ShellClash修改版规则 (by UlinoyaPed)', url: 'https://github.com/UlinoyaPed/ShellClash/raw/master/rules/ShellClash.ini', group: '定制规则', is_default: false },

        // Airport Specific (500-599) - Grouping under '机场专属' for now, can be specific if needed
        { id: 501, name: 'EXFLUX', url: 'https://gist.github.com/jklolixxs/16964c46bad1821c70fa97109fd6faa2/raw/EXFLUX.ini', group: '机场专属', is_default: false },
        { id: 502, name: 'NaNoport', url: 'https://gist.github.com/jklolixxs/32d4e9a1a5d18a92beccf3be434f7966/raw/NaNoport.ini', group: '机场专属', is_default: false },
        { id: 503, name: 'CordCloud', url: 'https://gist.github.com/jklolixxs/dfbe0cf71ffc547557395c772836d9a8/raw/CordCloud.ini', group: '机场专属', is_default: false },
        { id: 504, name: 'BigAirport', url: 'https://gist.github.com/jklolixxs/e2b0105c8be6023f3941816509a4c453/raw/BigAirport.ini', group: '机场专属', is_default: false },
        { id: 505, name: '跑路云', url: 'https://gist.github.com/jklolixxs/9f6989137a2cfcc138c6da4bd4e4cbfc/raw/PaoLuCloud.ini', group: '机场专属', is_default: false },
        { id: 506, name: 'WaveCloud', url: 'https://gist.github.com/jklolixxs/fccb74b6c0018b3ad7b9ed6d327035b3/raw/WaveCloud.ini', group: '机场专属', is_default: false },
        { id: 507, name: '几鸡', url: 'https://gist.github.com/jklolixxs/bfd5061dceeef85e84401482f5c92e42/raw/JiJi.ini', group: '机场专属', is_default: false },
        { id: 508, name: '四季加速', url: 'https://gist.github.com/jklolixxs/6ff6e7658033e9b535e24ade072cf374/raw/SJ.ini', group: '机场专属', is_default: false },
        { id: 509, name: 'ImmTelecom', url: 'https://gist.github.com/jklolixxs/24f4f58bb646ee2c625803eb916fe36d/raw/ImmTelecom.ini', group: '机场专属', is_default: false },
        { id: 510, name: 'AmyTelecom', url: 'https://gist.github.com/jklolixxs/b53d315cd1cede23af83322c26ce34ec/raw/AmyTelecom.ini', group: '机场专属', is_default: false },
        { id: 511, name: 'LinkCube', url: 'https://subweb.s3.fr-par.scw.cloud/RemoteConfig/customized/convenience.ini', group: '机场专属', is_default: false },
        { id: 512, name: 'Miaona', url: 'https://gist.github.com/jklolixxs/ff8ddbf2526cafa568d064006a7008e7/raw/Miaona.ini', group: '机场专属', is_default: false },
        { id: 513, name: 'Foo&Friends', url: 'https://gist.github.com/jklolixxs/df8fda1aa225db44e70c8ac0978a3da4/raw/Foo&Friends.ini', group: '机场专属', is_default: false },
        { id: 514, name: 'ABCloud', url: 'https://gist.github.com/jklolixxs/b1f91606165b1df82e5481b08fd02e00/raw/ABCloud.ini', group: '机场专属', is_default: false },
        { id: 515, name: '咸鱼', url: 'https://raw.githubusercontent.com/SleepyHeeead/subconverter-config/master/remote-config/customized/xianyu.ini', group: '机场专属', is_default: false },
        { id: 516, name: '便利店', url: 'https://subweb.oss-cn-hongkong.aliyuncs.com/RemoteConfig/customized/convenience.ini', group: '机场专属', is_default: false },
        { id: 517, name: 'CNIX', url: 'https://raw.githubusercontent.com/Mazeorz/airports/master/Clash/SSRcloud.ini', group: '机场专属', is_default: false },
        { id: 518, name: 'Nirvana', url: 'https://raw.githubusercontent.com/Mazetsz/ACL4SSR/master/Clash/config/V2rayPro.ini', group: '机场专属', is_default: false },
        { id: 519, name: 'V2Pro', url: 'https://raw.githubusercontent.com/Mazeorz/airports/master/Clash/V2Pro.ini', group: '机场专属', is_default: false },
        { id: 520, name: '史迪仔-自动测速', url: 'https://raw.githubusercontent.com/Mazeorz/airports/master/Clash/Stitch.ini', group: '机场专属', is_default: false },
        { id: 521, name: '史迪仔-负载均衡', url: 'https://raw.githubusercontent.com/Mazeorz/airports/master/Clash/Stitch-Balance.ini', group: '机场专属', is_default: false },
        { id: 522, name: 'Maying', url: 'https://raw.githubusercontent.com/SleepyHeeead/subconverter-config/master/remote-config/customized/maying.ini', group: '机场专属', is_default: false },
        { id: 523, name: 'Ytoo', url: 'https://subweb.s3.fr-par.scw.cloud/RemoteConfig/customized/ytoo.ini', group: '机场专属', is_default: false },
        { id: 524, name: 'w8ves', url: 'https://raw.nameless13.com/api/public/dl/M-We_Fn7/w8ves.ini', group: '机场专属', is_default: false },
        { id: 525, name: 'NyanCAT', url: 'https://raw.githubusercontent.com/SleepyHeeead/subconverter-config/master/remote-config/customized/nyancat.ini', group: '机场专属', is_default: false },
        { id: 526, name: 'Nexitally', url: 'https://subweb.s3.fr-par.scw.cloud/RemoteConfig/customized/nexitally.ini', group: '机场专属', is_default: false },
        { id: 527, name: 'SoCloud', url: 'https://raw.githubusercontent.com/SleepyHeeead/subconverter-config/master/remote-config/customized/socloud.ini', group: '机场专属', is_default: false },
        { id: 528, name: 'ARK', url: 'https://raw.githubusercontent.com/SleepyHeeead/subconverter-config/master/remote-config/customized/ark.ini', group: '机场专属', is_default: false },
        { id: 529, name: 'N3RO', url: 'https://gist.githubusercontent.com/tindy2013/1fa08640a9088ac8652dbd40c5d2715b/raw/n3ro_optimized.ini', group: '机场专属', is_default: false },
        { id: 530, name: 'Scholar', url: 'https://gist.githubusercontent.com/tindy2013/1fa08640a9088ac8652dbd40c5d2715b/raw/scholar_optimized.ini', group: '机场专属', is_default: false },
        { id: 531, name: 'Flowercloud', url: 'https://subweb.s3.fr-par.scw.cloud/RemoteConfig/customized/flower.ini', group: '机场专属', is_default: false },

        // Special (600+)
        { id: 601, name: 'NeteaseUnblock', url: 'https://raw.githubusercontent.com/SleepyHeeead/subconverter-config/master/remote-config/special/netease.ini', group: '特殊', is_default: false },
        { id: 602, name: 'Basic', url: 'https://raw.githubusercontent.com/SleepyHeeead/subconverter-config/master/remote-config/special/basic.ini', group: '特殊', is_default: false }
    ]
};
